---
- name: Install Zabbix agent packages
  package: 
    name:
      - zabbix-agent
    enablerepo: local-zabbix
    disablerepo: "*"
    state: present  

- name: Start and Enable Zabbix agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes

- name: Open Zabbix agent port
  firewalld:
    port: 10050/tcp
    state: enabled
    permanent: true
    immediate: true  


