---
- name: Install Zabbix server and web packages
  package:
    name: "{{item}}"
    enablerepo: local-zabbix
    disablerepo: "*"
    state: present
  loop:
      - zabbix-server-mysql
      - zabbix-agent
      - zabbix-web
      - zabbix-web-mysql
      - zabbix-sql-scripts
      - php
      - php-fpm
      - php-mysqlnd

- name: Open Zabbix server port 
  firewalld:
    port: 10051/tcp
    state: enabled
    permanent: true
    immediate: true




  
